name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Token padrão do GitHub

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token padrão do GitHub
          USERNAME: ViniciusProgrammer
          
      - name: Pull latest changes
        run: git pull origin ${GITHUB_REF##*/} --rebase

      - name: Commit & Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add profile-3d-contrib/
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push origin ${GITHUB_REF##*/}
